name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and analyze with SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=matheusribeiro02_WebServices_Completo -Dsonar.organization=matheusribeiro02 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Fail if coverage is below 50%
        run: |
          coverage=$(curl -s https://sonarcloud.io/api/measures/component?componentKey=matheusribeiro02_WebServices_Completo&metricKeys=coverage | jq -r '.component.measures[0].value')
          if (( $(echo "$coverage < 50.0" |bc -l) )); then
            echo "Test coverage is below 50%!"
            exit 1
          fi
