name: Testar Conexão PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  testar-conexao-postgresql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Set up PostgreSQL
      uses: postgresql/setup-postgres@v2
      with:
        postgresql-version: '14'
        database-url: 'postgres://postgres:senha@localhost:5432/jdbc'

    - name: Testar Conexão
      run: |
        psql -h localhost -U postgres -d jdbc -c "SELECT *;"
